#!/bin/bash

#Quick aliases
alias v="vim"
# alias ls="ls -hN --color=auto" # --group-directories-first
alias grep='grep --color=auto' # Color grep - highlight desired sequence
alias ccat='highlight --out-format=ansi' # Color cat - print file with syntax highlight
alias mkd='mkdir -pv'
alias fz='fzf-tmux'

tn() {
    tmux new -s $1
}

ta() {
    tmux a -t $1
}

ts() {
    tmux ls
}

#Useful
alias bot='cd $(dirname $(find . | tail -n 1))'
alias lsl="ls -ltrh"
alias ctags='ctags -R --exclude=.git --exclude=log --exclude=node_modules .'


#Docker
alias build="docker-compose build"
alias up="docker-compose up"
alias upbuild="docker-compose up --build"
alias dlogs="docker logs -f"

#AWS ECS
alias ecslogin="aws ecr get-login --no-include-email --region us-east-1 | bash"
